#!/bin/bash

basedir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

src_files="$basedir/src/*.js"

babel_call="node --max_old_space_size=4096 $basedir/node_modules/.bin/babel"
# The babel presets to use are configured in "$basedir/.babelrc".

mkdir -p $basedir/lib

export UV_THREADPOOL_SIZE=100
for src_file in $src_files
do
  lib_file="$(echo $src_file | sed 's/\(.*\)\/src\/\(.*\)\.js/\1\/lib\/\2\.js/g')"   
  echo "$src_file > $lib_file"
  $babel_call $src_file > $lib_file
done
